name: employee_management
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  provider: ^6.0.0
  equatable: ^2.0.5
  hive: ^2.2.3 
  hive_flutter: ^1.1.0 
  path_provider: ^2.1.5 
  intl: ^0.19.0
  table_calendar: ^3.1.2
  flutter_svg: ^2.0.14
  grouped_list: ^6.0.0
  uuid: ^4.5.1
  keyboard_attachable: 
    git:
      url: https://github.com/ryanaidilp/keyboard_attachable.git
      ref: master

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  
  


flutter_gen:
  integrations:
    flutter_svg: true

  assets:
    enabled: true


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  
